<h3>What is this?</h3>
<p>This is a handling module.  It allows adding a handling charge if the order total (before taxes and shipping) is below a set minimum.</p>

<h3>How Do I use It</h3>
<ol>
  <li>Install the module</li>
  <li>Set the module as the handling module in EcommerceExt module</li>
  <li>Set the handling price and the price at which the handling charge is no longer applied, in the module's admin panel.</li>
</ol>

<h3>Copyright and License</h3>
<p>Copyright &copy; 2024, CMS Made Simple Foundation <a href="mailto:info@cmsmadesimple.org">&lt;info@cmsmadesimple.org&gt;</a>. All Rights Are Reserved.</p>
<p>Copyright &copy; 2004-2017, Robert Campbell &lt;calguy1000&gt;. All Rights Are Reserved.</p>
<hr>
<p>This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.</p>
<p>However, as a special exception to the GPL, this software is distributed
as an addon module to CMS Made Simple.  You may not use this software
in any Non GPL version of CMS Made simple, or in any version of CMS
Made simple that does not indicate clearly and obviously in its admin
section that the site was built with CMS Made simple.</p>
<p>This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Or read it <a href="http://www.gnu.org/licenses/licenses.html#GPL">online</a></p>

<hr>
<h4>Current Maintainers</h4>
<ul>
  <li class="p_bottom_15"><strong>Christian Kvikant</strong></li>
</ul>

<h4>Past Maintainers</h4>
<ul>
  <li><strong>Robert Campbell (calguy1000)</strong> <br /></li>
</ul>
